# Generated by Django 5.2.5 on 2025-08-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("Nursery", "Nursery"),
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "1st"),
                            ("2", "2nd"),
                            ("3", "3rd"),
                            ("4", "4th"),
                            ("5", "5th"),
                            ("6", "6th"),
                            ("7", "7th"),
                            ("8", "8th"),
                            ("9", "9th"),
                            ("10", "10th"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "other_class",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("village", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=15)),
                ("photo", models.ImageField(upload_to="student_photos/")),
                (
                    "unique_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institution",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.partner",
                    ),
                ),
            ],
        ),
    ]
